[GLOBAL]
pants_version = "2.23.1"
colors = true
pantsd = true
level = "info"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.pylint",
  "pants.backend.python.lint.pydocstyle",
  "pants.backend.python.lint.bandit",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.autoflake",
  "pants.backend.python.lint.pyupgrade",

  "pants.backend.python.typecheck.mypy",
  "pants.backend.python.providers.experimental.pyenv",
  "pants.backend.python.test.pytest",

  "pants.backend.build_files.fmt.black",
  "pants.backend.shell",
  "pants.backend.shell.lint.shfmt",
  "pants.backend.shell.lint.shellcheck",
  "pants.backend.tools.preamble",
  "pants.backend.tools.taplo",



  "pants.backend.experimental.openapi",
  "pants.backend.experimental.openapi.lint.openapi_format",
  "pants.backend.experimental.python",
  "pants.backend.experimental.python.typecheck.pytype",
  "pants.backend.experimental.tools.semgrep",
  "pants.backend.experimental.tools.yamllint",
  "pants.backend.experimental.visibility",
]


[anonymous-telemetry]
enabled = false

[pytype]
install_from_resolve = "python-default"

[python]
interpreter_constraints = [">=3.11"]
enable_resolves = true
default_resolve = "python-default"

[python.resolves]
python-default = "gen_captions/lockfile.lock"

[source]
root_patterns = ["/"]

[pyenv-python-provider]
installation_extra_env_vars = []
url_platform_mapping = {}


[black]
args = ["--line-length=75"]

[isort]
args = ["--line-length=75"]

[flake8]
args = [
  "--extend-ignore=W291,W503",
  "--max-line-length=85",
  "--exclude=tests/*",
]


[bandit]
args = ["--skip=B101,B308", "--confidence"]

[pylint]
args = [
  "--disable=E1101",
  "--disable=C0103",
  "--ignore-paths=^tests/.*$",
  "--verbose",
  #"--help"
]

[pydocstyle]
args = ["--ignore=D200,D203,D212,D400,D213"]

[pytest]

[tailor]
ignore_paths = ["*"]

[python-infer]
unowned_dependency_behavior = "ignore"
string_imports = true
string_imports_min_dots = 2

[test]
output = "all"
report = false
use_coverage = true

[coverage-py]
global_report = true
